// examples/svelte-kit-example/src/lib/components/stagewise/ToolbarWrapper.svelte
<script lang="ts">
import type { ToolbarConfig } from '@stagewise/core';
import { onMount } from 'svelte';
import { browser } from '$app/environment';

export let config: ToolbarConfig;
let isLoaded = false;

onMount(async () => {
  if (isLoaded || !browser) return;
  isLoaded = true;

  const { initToolbar } = await import('@stagewise/core');
  initToolbar(config);
});
</script>

// examples/nuxt-example/components/stagewise/ToolbarWrapper.vue
<script setup lang="ts">
import type { ToolbarConfig } from '@stagewise/core';
import { initToolbar } from '@stagewise/core';
import { onMounted, ref } from 'vue';

const props = defineProps<{
  config: ToolbarConfig;
}>();

const isLoaded = ref(false);

onMounted(() => {
  if (isLoaded.value) return;
  isLoaded.value = true;
  initToolbar(props.config);
});
</script>

<template>
  <div></div>
</template>
