// examples/nuxt-example/components/stagewise/ToolbarWrapper.vue
<script setup lang="ts">
import type { ToolbarConfig } from '@stagewise/toolbar';
import { initToolbar } from '@stagewise/toolbar';
import { onMounted, ref } from 'vue';

const props = defineProps<{
  config: ToolbarConfig;
}>();

const isLoaded = ref(false);

onMounted(() => {
  if (isLoaded.value) return;
  isLoaded.value = true;
  initToolbar(props.config);
});
</script>

<template>
  <div></div>
</template>

// apps/next-playground/src/app/_components/toolbar-wrapper.tsx
'use client';
import type { ToolbarConfig } from '@stagewise/toolbar';
export type { ToolbarConfig };
import { initToolbar } from '@stagewise/toolbar';
import { useEffect, useRef } from 'react';

export default function ToolbarWrapper({ config }: { config: ToolbarConfig }) {
  const isLoaded = useRef(false);
  useEffect(() => {
    if (isLoaded.current) return;
    isLoaded.current = true;
    initToolbar(config);
  }, []);
  return null;
}
